import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[font]
size = 13.5
offset = { x = 0, y = 0 }
[font.normal]
family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = true
