#!/usr/bin/env zsh

# zsh
ln -vfs ~/.dotfiles/zsh/.zsh_profile ~
ln -vfs ~/.dotfiles/zsh/.zshrc ~

# nvim
ln -vfs ~/.dotfiles/nvim/.vimrc ~

# tmux
ln -vfs ~/.dotfiles/tmux/.tmux.conf ~ 

# bin

ln -vfs ~/.dotfiles/.local/.bin ~/.local 
