#!/usr/bin/env zsh

alias aic="aicommits --type conventional"

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# vim
alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias niff="nvim -d"

alias po="poetry"

alias cat="bat"

alias k=kubectl

# Shortcuts
alias reload_profile="source ~/.zsh_profile"
alias reload_shell="exec ${SHELL} -l"
alias week="date +%V"

alias localip="ipconfig getifaddr en0"

# dirs
alias l="ls"
alias ll="ls -l"
alias lla="ll -A"

alias cdd="cd .."
alias cddd="cd ../.."
alias cdddd="cd ../../.."
alias cddddd="cd ../../../.."

alias dot="cd ~/.dotfiles"
alias icloud="cd ~/Library/Mobile\ Documents/com\~apple\~CloudDocs"
alias notes='cd "/Users/nathan/Library/Mobile Documents/iCloud~md~obsidian/Documents/notes"'
alias steam='cd "/Users/nathan/Library/Application Support/Steam"'
alias rmdsstore="find . -type f -name '*.DS_Store' -ls -delete"

alias o="open ."
alias c="code ."

# env
alias work="source switch_env work"
alias personal="source switch_env personal"

# Show/hide hidden files in the Finder
alias showfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidefiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

alias urlencode='node --eval "console.log(encodeURIComponent(process.argv[1]))"'

alias reveal-md="reveal-md --theme night --highlight-theme hybrid --port 1337"

# Git
alias gs="git status"
alias gg="lazygit"
alias gd="git diff"

# aws
alias aws-profile='export AWS_PROFILE=$(sed -n "s/\[profile \(.*\)\]/\1/gp" ~/.aws/config | fzf)'

# pulumi
alias pul="pulumi"

rmbranch() {
  branchs=$(git branch --v | grep '\[gone\]' | awk '{print $1}')
  if [ -z "$branchs" ]; then
    echo "No branches to delete"
    return
  fi
  echo "Deleting branches:"
  echo $branchs | xargs -I{} sh -c 'git branch -D {} && echo Deleted {}'
}
