#!/usr/bin/env bash

alias aic="aicommits --type conventional"

alias vim="nvim"
alias vi="nvim"
alias niff="nvim -d"

alias python="python3"
alias pip="pip3"

alias pn="pnpm"
alias cat="bat"

alias k=kubectl

# Shortcuts
alias reload_profile="source ~/.zsh_profile"
alias reload_shell="exec ${SHELL} -l"
alias week="date +%V"
alias h="cd ~/dev/helosion"
alias m="cd ~/dev/mewo"

alias localip="ipconfig getifaddr en0"

alias l="ls"

alias ll="ls -l"
alias lla="ll -A"

alias cdd="cd .."
alias cddd="cd .. && cd .."

alias dot="cd ~/.dotfiles"
alias rmdsstore="find . -type f -name '*.DS_Store' -ls -delete"

alias o="open ."
alias c="code ."

# Show/hide hidden files in the Finder
alias showfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidefiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

alias urlencode='node --eval "console.log(encodeURIComponent(process.argv[1]))"'

alias reveal-md="reveal-md --theme night --highlight-theme hybrid --port 1337"

# Git
alias gs="git status"

alias rmbranch="git branch --v | grep '\[gone\]' | awk '{print $1}' | xargs git branch -D"

# Obsidian
alias notes="open -a 'Obsidian' ~/dev/notes"
